version: 2.1

jobs:
  build_and_push_backend:
    docker:
      - image: circleci/python:3.9  
    steps:
      - checkout  
      - setup_remote_docker:  
          version: 20.10.7  
          docker_layer_caching: true
      - run:
          name: Docker Build and Push Backend
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker build -t jayasurya5454/budget-buddy-backend:latest ./BudgetBuddy_backend
            docker push jayasurya5454/budget-buddy-backend:latest

  
  build_and_push_frontend:
    docker:
      - image: circleci/python:3.9  
    steps:
      - checkout  
      - setup_remote_docker:  
          version: 20.10.7  
          docker_layer_caching: true
      - run:
          name: Docker Build and Push Frontend
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker build -t jayasurya5454/budget-buddy-frontend:latest ./BudgetBuddy_frontend
            docker push jayasurya5454/budget-buddy-frontend:latest

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push_backend
      - build_and_push_frontend
